project:
  type: website
  output-dir: docs

website:
  title: "YY-Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/YongY-Github
      - icon: linkedin
        href: https://linkedin.com
format:
  html:
    theme: cosmo
    css: styles.css



